// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqsmjpzozjzjpzxzehbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxc21qcHpvemp6anB6eHplaGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODM2MjQsImV4cCI6MjA1ODQ1OTYyNH0.wH7xD86J9OTx6eruGJ6cKMOLpJ9--qAe0uotnAnuSL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);