// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvtnlrtklgcitpclafxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52dG5scnRrbGdjaXRwY2xhZnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzAzMTcsImV4cCI6MjA1ODUwNjMxN30.Iv-OEnWfxuhmD_ZTN79RTbMbr8wwZtqxlZZIkxXgH-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);